server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    allow-circular-references: true
  cloud:
    gateway:
      routes:
        - id: resource-server
          uri: lb://RESOURCE-SERVER
          predicates:
            - Path=/resources/**

eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
