server:
  port: 8080
zuul:
  routes:
    resources:
      path: /resources/**
      service-id: resource-server

spring:
  application:
    name: api-gateway
  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
